version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: Capstone_admin
      POSTGRES_PASSWORD: Olayinka789
      POSTGRES_DB: ecommerce
    ports:
      - "5435:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
      - ./data:/data
      - ./infra_scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
